# Generated by Django 5.2.13 on 2026-05-24 21:13

import django.core.serializers.json
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import nautobot.extras.models.statuses
import nautobot.ipam.fields
import nautobot_scanner.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0084_add_module_type_image_support'),
        ('extras', '0142_remove_scheduledjob_approval_required'),
        ('ipam', '0055_rename_ipaddress_ip_version_host_mask_length_ipam_ipaddr_ip_vers_d82ba5_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveredHost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('ip_address', nautobot.ipam.fields.VarbinaryIPField(db_index=True)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('os_family', models.CharField(blank=True, max_length=64)),
                ('os_type', models.CharField(blank=True, max_length=128)),
                ('os_accuracy', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('host_state', models.CharField(db_index=True, default='unknown', max_length=16)),
                ('linked_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_hosts', to='dcim.device')),
                ('linked_ipaddress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_hosts', to='ipam.ipaddress')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'discovered host',
                'verbose_name_plural': 'discovered hosts',
                'ordering': ('ip_address',),
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DiscoveredPort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('port', models.PositiveIntegerField()),
                ('protocol', models.CharField(max_length=8)),
                ('state', models.CharField(max_length=16)),
                ('service_name', models.CharField(blank=True, max_length=64)),
                ('banner', models.TextField(blank=True)),
                ('product', models.CharField(blank=True, max_length=128)),
                ('version', models.CharField(blank=True, max_length=64)),
                ('extra_info', models.CharField(blank=True, max_length=255)),
                ('cpe', models.JSONField(blank=True, default=list)),
                ('discovered_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='nautobot_scanner.discoveredhost')),
            ],
            options={
                'verbose_name': 'discovered port',
                'verbose_name_plural': 'discovered ports',
                'ordering': ('discovered_host', 'protocol', 'port'),
                'unique_together': {('discovered_host', 'port', 'protocol')},
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('status', models.CharField(db_index=True, default='pending', max_length=16)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('ingestion_token', models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ('raw_xml', models.FileField(blank=True, null=True, upload_to='scanner/xml/%Y/%m/')),
                ('raw_xml_size', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('job_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='extras.jobresult')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
                ('target_ipaddresses', models.ManyToManyField(blank=True, related_name='scans', to='ipam.ipaddress')),
                ('target_prefixes', models.ManyToManyField(blank=True, related_name='scans', to='ipam.prefix')),
            ],
            options={
                'verbose_name': 'scan',
                'verbose_name_plural': 'scans',
                'ordering': ('-started_at', '-created'),
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.AddField(
            model_name='discoveredhost',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='nautobot_scanner.scan'),
        ),
        migrations.CreateModel(
            name='ScannerAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('agent_type', models.CharField(default='local', max_length=16)),
                ('last_seen', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.CharField(blank=True, max_length=64)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dcim.location')),
                ('status', nautobot.extras.models.statuses.StatusField(default=nautobot_scanner.utils.get_default_status, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='extras.status')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanner_agent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'scanner agent',
                'verbose_name_plural': 'scanner agents',
                'ordering': ('name',),
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.AddField(
            model_name='scan',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scans', to='nautobot_scanner.scanneragent'),
        ),
        migrations.CreateModel(
            name='ScanProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('scan_type', models.CharField(max_length=16)),
                ('nmap_arguments', models.TextField()),
                ('timing_template', models.CharField(default='T3', max_length=4)),
                ('enabled_scripts', models.JSONField(blank=True, default=list)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'scan profile',
                'verbose_name_plural': 'scan profiles',
                'ordering': ('name',),
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.AddField(
            model_name='scan',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scans', to='nautobot_scanner.scanprofile'),
        ),
        migrations.CreateModel(
            name='TraceRouteHop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('hop_number', models.PositiveSmallIntegerField()),
                ('hop_ip', nautobot.ipam.fields.VarbinaryIPField(db_index=True)),
                ('hop_hostname', models.CharField(blank=True, max_length=255)),
                ('rtt_ms', models.FloatField(blank=True, null=True)),
                ('discovered_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traceroute_hops', to='nautobot_scanner.discoveredhost')),
            ],
            options={
                'verbose_name': 'traceroute hop',
                'verbose_name_plural': 'traceroute hops',
                'ordering': ('discovered_host', 'hop_number'),
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nse_script', models.CharField(max_length=128)),
                ('output', models.TextField()),
                ('severity', models.CharField(db_index=True, default='unknown', max_length=16)),
                ('references', models.JSONField(blank=True, default=list)),
                ('discovered_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='nautobot_scanner.discoveredport')),
            ],
            options={
                'verbose_name': 'vulnerability finding',
                'verbose_name_plural': 'vulnerability findings',
                'ordering': ('-severity', 'nse_script'),
            },
        ),
        migrations.AddIndex(
            model_name='discoveredhost',
            index=models.Index(fields=['ip_address', 'host_state'], name='nautobot_sc_ip_addr_d42e7d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='discoveredhost',
            unique_together={('scan', 'ip_address')},
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['agent', 'status'], name='nautobot_sc_agent_i_f4030a_idx'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['status', 'started_at'], name='nautobot_sc_status_e56b29_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='traceroutehop',
            unique_together={('discovered_host', 'hop_number')},
        ),
    ]
