# Generated by Django 5.2.13 on 2026-05-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_scanner', '0002_seed_default_scan_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoveredport',
            name='product',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='discoveredport',
            name='service_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='discoveredport',
            name='version',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
