# Generated by Django 5.2.15 on 2026-07-07 19:15

import django.contrib.postgres.fields.ranges
import nautobot_scanner.models.results
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_scanner', '0023_seed_provisional_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoveredhost',
            name='entry_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='discoveredhost',
            name='recorded_during',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(default=nautobot_scanner.models.results._open_belief_window),
        ),
    ]
