"""Smoke test: dispatch a real LocalBackend scan against 127.0.0.1.

Run from the host like:

    docker compose -f development/docker-compose.yml \
      --env-file development/.env exec -T nautobot-web \
      nautobot-server shell < development/scripts/smoke_local_scan.py

Validates the full pipeline:
- nmap subprocess actually executes
- raw XML gets gzipped to the FileField
- parser.parse_xml → parser.persist creates ORM records
- summary stats populate

Idempotent: re-fetches/recreates the demo Prefix and ScanProfile each run.
"""

from nautobot.extras.models import Status
from nautobot.ipam.models import Namespace, Prefix

from nautobot_scanner.backends import LocalBackend
from nautobot_scanner.choices import (
    ScanStateChoices,
    ScanTypeChoices,
    TimingTemplateChoices,
)
from nautobot_scanner.models import Scan, ScannerAgent, ScanProfile

print("=" * 70)
print("Scanner smoke test — local backend, 127.0.0.1 discovery scan")
print("=" * 70)

active = Status.objects.get(name="Active")

agent = ScannerAgent.objects.filter(agent_type="local").first()
if not agent:
    agent = ScannerAgent.objects.create(name="smoke-local", agent_type="local", status=active)
    print(f"Created agent: {agent.name}")
else:
    print(f"Using agent: {agent.name}")

profile, created = ScanProfile.objects.get_or_create(
    name="smoke-discovery",
    defaults={
        "scan_type": ScanTypeChoices.DISCOVERY,
        "nmap_arguments": "-sn",
        "timing_template": TimingTemplateChoices.T4,
        "description": "Generated by smoke_local_scan.py",
    },
)
print(f"{'Created' if created else 'Using'} profile: {profile.name} ({profile.nmap_arguments})")

ns = Namespace.objects.get(name="Global")
loopback, created = Prefix.objects.get_or_create(
    prefix="127.0.0.0/30",
    namespace=ns,
    defaults={"status": active, "description": "Smoke-test loopback range"},
)
print(f"{'Created' if created else 'Using'} target prefix: {loopback.prefix}")

scan = Scan.objects.create(agent=agent, profile=profile)
scan.target_prefixes.add(loopback)
print(f"Created scan: {scan.pk}")

print("\nDispatching LocalBackend.dispatch()...")
LocalBackend().dispatch(scan)
scan.refresh_from_db()

print(f"\nFinal scan state: {scan.status}")
print(f"  started_at:  {scan.started_at}")
print(f"  completed_at: {scan.completed_at}")
print(f"  summary:     {scan.summary}")
print(f"  error:       {scan.error_message or '(none)'}")
print(f"  raw_xml:     {scan.raw_xml.name} ({scan.raw_xml_size} bytes uncompressed)")
print(f"  hosts:       {scan.hosts.count()}")
for h in scan.hosts.all():
    print(f"    - {h.ip_address}  state={h.host_state}  hostname={h.hostname or '(none)'}")

assert scan.status == ScanStateChoices.COMPLETED, f"Expected COMPLETED, got {scan.status}"
assert scan.raw_xml.name, "raw_xml not stored"
assert scan.hosts.exists(), "no DiscoveredHost records created"
print("\n[PASS] all assertions met — pipeline is healthy.")
